name             'classroom'
maintainer       'Kennon Kwok'
maintainer_email 'kennon@getchef.com'
license          'All rights reserved'
description      'Installs/Configures codebox classroom'
long_description 'Installs/Configures codebox classroom'
version          '0.3.4'

depends 'build-essential'
depends 'docker'
depends 'ohai'
